config/routes.rb
RTedServiceRails::Application.routes.draw do

  get "admin/index"

  devise_for :users

  get "day_hist_rss/index"
  get "dayhist_updater/tedhist"
  get "hist_updater/autoupdate"
  
  resources :home, :only => [:index]
  resources :day_hists, :only => [:index]
  resources :ted_data, :only => [:index]
  resources :solar_img, :only => [:index]
  resources :water_img, :only => [:index]
  resources :admin, :only => [:index]
  resources :day_powers, :only => [:index, :show, :destroy]
  resources :power_graph, :only => [:index]
  
  post "tedpostserver/init"
  post "tedpostserver/postdata"

  root :to => 'home#index'

  match 'tedpostserver/init/' => 'tedpostserver#init', :via => :post, :defaults => {:format => 'xml'}
  match 'tedpostserver/postdata/' => 'tedpostserver#postdata', :via => :post, :defaults => {:format => 'xml'}
  match 'dayhist_updater/autoupdate' => 'dayhist_updater#autoupdate', :via => :get
  match 'admin/updateday' => 'admin#updateday', :via => :get
  match 'admin/loadtestdata' => 'admin#loadtestdata', :via => :get
end

app/controllers/power_graph_controller.rb
class PowerGraphController < ApplicationController
  def index
      
    @graphType = params[:graphType]
    if (@graphType == nil) then
      @graphType = "bar"
    end
    
    if (@graphType == "time")
      limit = 365
    elsif (@graphType == "table")
      limit = 30
    else
      # sleazy...
      @graphType = "bar"
      limit = 7
    end
    
    @dayPowersResult = DayPower.limit(limit).order( "day DESC" )
    
    render :template => 'power_graph/index.html.erb'
  end

  def show
  end
end

app/helpers/power_graph_helper.rb
module PowerGraphHelper
end

app/views/power_graph/index.html.erb
 <script type='text/javascript' src='http://www.google.com/jsapi'></script>
  <script type='text/javascript'>
    google.load('visualization', '1', {'packages':['annotatedtimeline','corechart','table' ]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
      <% if @graphType == "bar" %>
      data.addColumn('string', 'Date');
      <% else %>
      data.addColumn('date', 'Date');
      <% end %>
      data.addColumn('number', 'PGE');
      data.addColumn('number', 'Solar');
      data.addColumn('number', 'Net');
      data.addColumn('number', 'Water');
      data.addRows([
      <% @dayPowersResult.each do |dp| %>
        
        <% if @graphType == "bar" %>
        ["<%= dp.day.strftime("%m/%d/%Y") %>", <%= dp.pgeWatts %>, <%= dp.solarWatts %>, <%= dp.pgeWatts + dp.solarWatts %>, <%= dp.waterWatts %> ],
        <% else %>
        [new Date(<%= dp.day.year %>, <%= dp.day.month - 1 %>, <%= dp.day.day %>), <%= dp.pgeWatts %>, <%= dp.solarWatts %>, <%= dp.pgeWatts + dp.solarWatts %>, <%= dp.waterWatts %> ],
        <% end %>

      <% end %>
      ]);

      <% if @graphType == "bar" %>
      var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
      var options = {
          vAxis: {title: "Day"},
          hAxis: {title: "Consumption"},
          colors: ['red', 'green', 'grey', 'blue']
      };
      <% elsif @graphType == "table" %>
      var chart = new google.visualization.Table(document.getElementById('chart_div'));
      var options = {};
      <% elsif @graphType == "time" %>
      var chart = new google.visualization.AnnotatedTimeLine(document.getElementById('chart_div'));
      var options = {
        displayAnnotations: false,
        colors: ['red', 'green', 'grey', 'blue']
      };
      <% end %>
      chart.draw(data, options );
    }
  </script>

  <div id='chart_div' style='width: 700px; height: 400px;'></div>
  <p>&nbsp;<p>&nbsp;
  <div class="well">
  <form action=<%= power_graph_index_path %> >
  <p>Graph Options
      <select name="graphType">
        <option value="time" <% if @graphType == "time" %> selected <% end %>>Time</option>
        <option value="bar" <% if @graphType == "bar" %> selected <% end %>>Bar</option>
        <option value="table" <% if @graphType == "table" %> selected <% end %>>Table</option>
      </select>
      <p><input type="submit" value="Set Options">
  </form>
  </div>

app/views/power_graph/show.html.erb
<h1>PowerGraph#show</h1>
<p>Find me in app/views/power_graph/show.html.erb</p>